"""
Social Media Publishing Service
Handles OAuth and direct posting to LinkedIn, Twitter/X, and other platforms.
Uses official APIs for real posting (not mockups).
"""

import os
import httpx
from typing import Optional, Dict, Any
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from the .env file in the fastapi directory
env_path = Path(__file__).parents[2] / '.env'
load_dotenv(dotenv_path=env_path)

# OAuth credentials (set in .env)
LINKEDIN_CLIENT_ID = os.getenv("LINKEDIN_CLIENT_ID", "")
LINKEDIN_CLIENT_SECRET = os.getenv("LINKEDIN_CLIENT_SECRET", "")
TWITTER_API_KEY = os.getenv("TWITTER_API_KEY", "")
TWITTER_API_SECRET = os.getenv("TWITTER_API_SECRET", "")
TWITTER_BEARER_TOKEN = os.getenv("TWITTER_BEARER_TOKEN", "")


class SocialPublishingService:
    """Handles publishing content to social media platforms."""

    def __init__(self):
        self.linkedin_api = "https://api.linkedin.com/v2"
        self.twitter_api = "https://api.twitter.com/2"

    # ========== LINKEDIN ==========

    async def publish_to_linkedin(self, access_token: str, text: str, image_url: Optional[str] = None) -> Dict[str, Any]:
        """
        Post to LinkedIn using the LinkedIn API v2.
        Requires a valid OAuth2 access token with w_member_social scope.
        """
        if not access_token:
            return {"success": False, "error": "No LinkedIn access token. Connect your account first.", "platform": "linkedin"}

        async with httpx.AsyncClient() as client:
            try:
                # Step 1: Get user profile URN
                # Try OpenID userinfo first
                profile_resp = await client.get(
                    f"{self.linkedin_api}/userinfo",
                    headers={"Authorization": f"Bearer {access_token}"}
                )
                
                if profile_resp.status_code != 200:
                    # Fallback to legacy /me endpoint if openid scope isn't fully active
                    profile_resp = await client.get(
                        f"{self.linkedin_api}/me",
                        headers={"Authorization": f"Bearer {access_token}"}
                    )
                
                if profile_resp.status_code != 200:
                    error_detail = profile_resp.text
                    if profile_resp.status_code == 401:
                        return {
                            "success": False, 
                            "error": "REVOKED_ACCESS_TOKEN", 
                            "detail": error_detail,
                            "platform": "linkedin"
                        }
                    return {"success": False, "error": f"Failed to get LinkedIn profile: {error_detail}", "platform": "linkedin"}
                
                profile = profile_resp.json()
                # Handle different ID formats between /userinfo (sub) and /me (id)
                person_id = profile.get('sub') or profile.get('id')
                person_urn = f"urn:li:person:{person_id}"

                # Step 2: Create the post
                post_data = {
                    "author": person_urn,
                    "lifecycleState": "PUBLISHED",
                    "specificContent": {
                        "com.linkedin.ugc.ShareContent": {
                            "shareCommentary": {
                                "text": text
                            },
                            "shareMediaCategory": "NONE"
                        }
                    },
                    "visibility": {
                        "com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"
                    }
                }

                # If image URL is provided, include it
                if image_url:
                    asset_urn = await self._upload_linkedin_image(client, access_token, person_urn, image_url)
                    if asset_urn:
                        post_data["specificContent"]["com.linkedin.ugc.ShareContent"]["shareMediaCategory"] = "IMAGE"
                        post_data["specificContent"]["com.linkedin.ugc.ShareContent"]["media"] = [{
                            "status": "READY",
                            "description": {"text": "Generated by FOAI"},
                            "media": asset_urn,
                            "title": {"text": "FOAI Content"}
                        }]
                    else:
                        print("WARNING: LinkedIn image upload failed, falling back to text-only post")

                resp = await client.post(
                    f"{self.linkedin_api}/ugcPosts",
                    headers={
                        "Authorization": f"Bearer {access_token}",
                        "Content-Type": "application/json",
                        "X-Restli-Protocol-Version": "2.0.0"
                    },
                    json=post_data,
                    timeout=30.0
                )

                if resp.status_code in (200, 201):
                    post_id = resp.headers.get("x-restli-id", resp.json().get("id", ""))
                    return {
                        "success": True,
                        "post_id": post_id,
                        "post_url": f"https://www.linkedin.com/feed/update/{post_id}",
                        "platform": "linkedin"
                    }
                else:
                    return {"success": False, "error": f"LinkedIn API error: {resp.text}", "platform": "linkedin"}

            except Exception as e:
                return {"success": False, "error": str(e), "platform": "linkedin"}

    async def _upload_linkedin_image(self, client: httpx.AsyncClient, access_token: str, person_urn: str, image_url: str) -> Optional[str]:
        """
        Uploads an image to LinkedIn and returns the asset URN.
        Follows the 3-step process: Register -> Upload -> Post
        """
        try:
            # Step 1: Register the upload
            register_url = f"{self.linkedin_api}/assets?action=registerUpload"
            register_data = {
                "registerUploadRequest": {
                    "recipes": ["urn:li:digitalmediaRecipe:feedshare-image"],
                    "owner": person_urn,
                    "serviceRelationships": [
                        {
                            "relationshipType": "OWNER",
                            "identifier": "urn:li:userGeneratedContent"
                        }
                    ]
                }
            }
            
            reg_resp = await client.post(
                register_url,
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Content-Type": "application/json"
                },
                json=register_data
            )
            
            if reg_resp.status_code != 200:
                print(f"ERROR: LinkedIn Register Upload failed: {reg_resp.text}")
                return None
            
            reg_json = reg_resp.json()
            upload_url = reg_json["value"]["uploadMechanism"]["com.linkedin.digitalmedia.uploading.MediaUploadHttpRequest"]["uploadUrl"]
            asset_urn = reg_json["value"]["asset"]
            
            # Step 2: Download the image from Supabase
            img_resp = await client.get(image_url)
            if img_resp.status_code != 200:
                print(f"ERROR: Failed to download image from {image_url}")
                return None
            
            # Step 3: Upload the image binary to LinkedIn
            upload_resp = await client.post(
                upload_url,
                headers={
                    "Authorization": f"Bearer {access_token}",
                    "Content-Type": "application/octet-stream"
                },
                content=img_resp.content
            )
            
            if upload_resp.status_code not in (200, 201):
                print(f"ERROR: LinkedIn Image Upload failed: {upload_resp.text}")
                return None
                
            return asset_urn
            
        except Exception as e:
            print(f"ERROR: LinkedIn image upload process failed: {e}")
            return None

    def get_linkedin_auth_url(self, redirect_uri: str) -> str:
        """Generate LinkedIn OAuth2 authorization URL."""
        import secrets
        state = secrets.token_urlsafe(32)
        return (
            f"https://www.linkedin.com/oauth/v2/authorization?"
            f"response_type=code&client_id={LINKEDIN_CLIENT_ID}"
            f"&redirect_uri={redirect_uri}"
            f"&scope=openid%20profile%20w_member_social"
            f"&state={state}"
        )

    async def exchange_linkedin_code(self, code: str, redirect_uri: str) -> Dict[str, Any]:
        """Exchange authorization code for LinkedIn access token."""
        async with httpx.AsyncClient() as client:
            resp = await client.post(
                "https://www.linkedin.com/oauth/v2/accessToken",
                data={
                    "grant_type": "authorization_code",
                    "code": code,
                    "redirect_uri": redirect_uri,
                    "client_id": LINKEDIN_CLIENT_ID,
                    "client_secret": LINKEDIN_CLIENT_SECRET,
                },
                headers={"Content-Type": "application/x-www-form-urlencoded"}
            )
            if resp.status_code == 200:
                return resp.json()
            return {"error": resp.text}

    # ========== TWITTER / X ==========

    async def publish_to_twitter(self, access_token: str, text: str, image_url: Optional[str] = None) -> Dict[str, Any]:
        """
        Post a tweet using the Twitter API v2.
        Requires OAuth 2.0 User Context with tweet.write scope.
        """
        if not access_token:
            return {"success": False, "error": "No Twitter access token. Connect your account first.", "platform": "twitter"}

        async with httpx.AsyncClient() as client:
            try:
                tweet_data: Dict[str, Any] = {"text": text}

                # If image, upload it first via v1.1 media upload
                if image_url:
                    media_id = await self._upload_twitter_media(access_token, image_url)
                    if media_id:
                        tweet_data["media"] = {"media_ids": [media_id]}

                resp = await client.post(
                    f"{self.twitter_api}/tweets",
                    headers={
                        "Authorization": f"Bearer {access_token}",
                        "Content-Type": "application/json"
                    },
                    json=tweet_data,
                    timeout=30.0
                )

                if resp.status_code in (200, 201):
                    data = resp.json().get("data", {})
                    tweet_id = data.get("id", "")
                    return {
                        "success": True,
                        "post_id": tweet_id,
                        "post_url": f"https://twitter.com/i/web/status/{tweet_id}",
                        "platform": "twitter"
                    }
                else:
                    error_detail = resp.text
                    if resp.status_code == 401:
                        return {
                            "success": False, 
                            "error": "UNAUTHORIZED", 
                            "detail": error_detail,
                            "platform": "twitter"
                        }
                    return {"success": False, "error": f"Twitter API error: {error_detail}", "platform": "twitter"}

            except Exception as e:
                return {"success": False, "error": str(e), "platform": "twitter"}

    async def _upload_twitter_media(self, access_token: str, image_url: str) -> Optional[str]:
        """Download image from URL and upload to Twitter media endpoint."""
        try:
            async with httpx.AsyncClient() as client:
                # Download the image
                img_resp = await client.get(image_url)
                if img_resp.status_code != 200:
                    return None

                # Upload to Twitter v1.1 media/upload
                resp = await client.post(
                    "https://upload.twitter.com/1.1/media/upload.json",
                    headers={"Authorization": f"Bearer {access_token}"},
                    files={"media_data": img_resp.content}
                )
                if resp.status_code == 200:
                    return resp.json().get("media_id_string")
        except Exception as e:
            print(f"Twitter media upload failed: {e}")
        return None

    def get_twitter_auth_url(self, redirect_uri: str) -> str:
        """Generate Twitter OAuth2 authorization URL (PKCE flow)."""
        import secrets
        state = secrets.token_urlsafe(32)
        return (
            f"https://twitter.com/i/oauth2/authorize?"
            f"response_type=code&client_id={TWITTER_API_KEY}"
            f"&redirect_uri={redirect_uri}"
            f"&scope=tweet.read%20tweet.write%20users.read%20offline.access"
            f"&state={state}&code_challenge=challenge&code_challenge_method=plain"
        )

    async def exchange_twitter_code(self, code: str, redirect_uri: str) -> Dict[str, Any]:
        """Exchange authorization code for Twitter access token."""
        async with httpx.AsyncClient() as client:
            resp = await client.post(
                "https://api.twitter.com/2/oauth2/token",
                data={
                    "grant_type": "authorization_code",
                    "code": code,
                    "redirect_uri": redirect_uri,
                    "client_id": TWITTER_API_KEY,
                    "code_verifier": "challenge",
                },
                headers={"Content-Type": "application/x-www-form-urlencoded"},
                auth=(TWITTER_API_KEY, TWITTER_API_SECRET)
            )
            if resp.status_code == 200:
                return resp.json()
            return {"error": resp.text}

    # ========== GENERIC PUBLISH ==========

    async def publish(self, platform: str, access_token: str, text: str, image_url: Optional[str] = None) -> Dict[str, Any]:
        """Route to the correct platform publisher."""
        if platform == "linkedin":
            return await self.publish_to_linkedin(access_token, text, image_url)
        elif platform == "twitter":
            return await self.publish_to_twitter(access_token, text, image_url)
        else:
            return {"success": False, "error": f"Platform '{platform}' not supported for direct publishing", "platform": platform}


# Global Instance
social_service = SocialPublishingService()
